name: A workflow to set default path and run executables
on: push
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4
    - name: Run a script
      run: bash my-script.sh
