name: "Hello World Action"
description: "A simple action that prints a message"
inputs:
    MY_NAME:
        description: "The name to greet"
        required: true
runs:
    using: "node12"
    main: "entrypoint.sh" # Or use "entrypoint.sh" for shell script actions
