name: "Bash Script Action"
description: "An action to run a Bash script"
inputs:
    MY_NAME:
        description: "The name to greet"
        required: true
runs:
    using: "composite"
    steps:
      - run: ./entrypoint.sh ${{ inputs.MY_NAME }}
        shell: bash
