name: 'Hello World Action'
description: 'A simple hello world action'
inputs:
    MY_NAME:
        description: 'The name to greet'
        required: true
runs:
    using: "composite"
    steps:
    - name: Entry point Executable 
      run: |
      pwd
      ls
      shell: bash
   
